[project]
name = "mp3-id3-check"
version = "0.1.0"
description = "check mp3 files for a set of expected id3 tags"
authors = [{ name = "Ralph Depping", email = "github@depping.me" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mutagen>=1.46.0",
]

[tool.uv]
system-certs = true

[[tool.uv.index]]
name = "cloudsmith"
url = "https://dl.cloudsmith.io/basic/secure-apps/app-repo/python/simple/"
default = true

[project.scripts]
mp3-id3-check = "mp3_id3_check.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mp3_id3_check"]
